apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "BSC(jang4sc@hanmail.net)"
    buildDate: "20220812"
    imageRegistry: "docker.io/library/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80