---
kind: Service
apiVersion: v1
metadata:
  name: webapp-loadbalancer-svc
spec:
  type: LoadBalancer
  clusterIP: 10.100.10.10
  selector: 
    app: webapp
  ports:
    - port: 80
      targetPort: 80