---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-sts
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: mysts
    template:
      metadata:
        name: nginx-pod
        labels:
          app: mysts
      spec:
        containers:
        - name: nginx-container
          image: nginx:1.15
          ports:
          - containerPort: 80