kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: web-deploy
  annotations:
    kubernetes.io/change-cause: "version 2.2"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache
  template:
    metadata:
      labels:   
        name: apache
        app: main
        rel: stable
        tier: frontend
    spec:       
      containers:
      - name: mainui-container 
        image: httpd:2.2        
        ports:                
        - containerPort: 80
          protocol: TCP
